modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Apache-2.0"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/infernalexp/Mining-Master/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "miningmaster" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName = "Mining Master" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://infernalstudios.org/api/mods/miningmaster/forge" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://discord.gg/UYGSn94" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "Mining_Master_Banner.png" #optional

# A text field displayed in the mod UI
credits = "See the description!" #optional

# A text field displayed in the mod UI
authors = "Infernal Studios" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''
Mining Master is a mod that adds 10 new 'Enchanting Ores' to the game. These ores, when applied to a tool or armour-piece on a Smithing Table, bestow an Enchantment!
Using further Enchanting Ores on the same piece of equipment will up the enchantment level, too. It also adds 10 new enchantments that are associated with these gems!

It's a small mod, but we think it'll add a lot! We hope you enjoy it! :D

Credits
HellionGames, SwanX1 - Developers
Nekomaster1000 - Conceptualiser, 2D & 3D Artist,
GLaDOS Edition, Luxintrus, TheCraftyGhost - Additional 2D Artists
Reetam - Meteorite Concept

Thank you to Mickelus for helping with Tetra compatibility features!
'''

[[dependencies.miningmaster]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.miningmaster]]
modId="minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side="BOTH"